// src/core/sequence.rs
use crate::utils::config::SamplingParams;
use crate::utils::image::ImageData;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone, Copy)]
pub enum SequenceStatus {
    Waiting,
    Running,
    Finished,
    Cached,        //Finished but resources not freed
    Swapped,       //kv cache swapped to CPU memory (may not finished)
    FinishSwapped, //Finished and kv cache swapped to CPU memory
}

impl fmt::Display for SequenceStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            SequenceStatus::Waiting => "Waiting",
            SequenceStatus::Running => "Running",
            SequenceStatus::Finished => "Finished",
            SequenceStatus::Cached => "Cached",
            SequenceStatus::Swapped => "Swapped",
            SequenceStatus::FinishSwapped => "FinishSwapped",
        };
        write!(f, "{}", s)
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Sequence {
    pub id: usize,
    pub created_time: usize,
    pub request_arrival_time: usize,
    pub first_token_time: Option<usize>,
    pub swapped_time: Option<usize>,
    pub status: SequenceStatus,
    pub token_ids: Vec<u32>,
    pub output_ids: Vec<u32>,
    pub block_table: Vec<u32>,
    pub num_cached_tokens: usize,
    pub mamba_prefix_hash: Option<u64>,
    pub last_token: u32,
    pub block_size: usize,
    pub sampling_params: SamplingParams,
    pub pd_first_token: Option<u32>, // the first token generated by PD server
    pub images: Option<ImageData>,   // Multimodel image data
    pub is_tool_call_end: bool,
    pub hit_stop_sequence: bool,
    pub stop_sequence: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DecodeSequence {
    pub id: usize,
    pub last_token: u32,
    pub len: usize,
    pub last_block_tokens: usize,
    pub block_table_last: u32,
    pub block_tables: Vec<u32>,
    pub sampling_params: SamplingParams,
}

impl DecodeSequence {
    pub fn new(sequence: &Sequence) -> Self {
        let last_token = sequence.last_token;
        let len = sequence.len();
        let last_block_tokens = sequence.last_block_num_tokens();
        let block_table_last = *sequence.block_table.last().unwrap();
        DecodeSequence {
            id: sequence.id,
            last_token,
            len,
            last_block_tokens,
            block_table_last,
            block_tables: sequence.block_table.clone(),
            sampling_params: sequence.sampling_params.clone(),
        }
    }

    pub fn tokens_len(&self) -> usize {
        self.len
    }
}

pub trait ToDecodeInput {
    fn last_token(&self) -> u32;
    fn len(&self) -> usize;
    fn last_block_tokens(&self) -> usize;
    fn block_table_last(&self) -> u32;
    fn block_table(&self) -> &Vec<u32>;
    fn id(&self) -> usize;
}

impl ToDecodeInput for DecodeSequence {
    fn last_token(&self) -> u32 {
        self.last_token
    }

    fn len(&self) -> usize {
        self.len
    }

    fn last_block_tokens(&self) -> usize {
        self.last_block_tokens
    }

    fn block_table_last(&self) -> u32 {
        self.block_table_last
    }

    fn block_table(&self) -> &Vec<u32> {
        &self.block_tables
    }

    fn id(&self) -> usize {
        self.id
    }
}

impl ToDecodeInput for &Sequence {
    fn last_token(&self) -> u32 {
        self.last_token
    }

    fn len(&self) -> usize {
        self.tokens_len()
    }

    fn last_block_tokens(&self) -> usize {
        self.last_block_num_tokens()
    }

    fn block_table_last(&self) -> u32 {
        *self.block_table.last().unwrap()
    }

    fn block_table(&self) -> &Vec<u32> {
        &self.block_table
    }

    fn id(&self) -> usize {
        self.id
    }
}

impl Sequence {
    pub fn new(
        token_ids: Vec<u32>,
        block_size: usize,
        sampling_params: SamplingParams,
        images: &Option<ImageData>,
        image_idx: i32,
    ) -> Self {
        let images = if let Some(img) = &images {
            let mut img = img.clone(); // update the images
            img.image_idx = image_idx;
            Some(img)
        } else {
            None
        };
        Self {
            id: 0, // Will be set by scheduler
            created_time: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("Time went backwards")
                .as_millis() as usize,
            request_arrival_time: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("Time went backwards")
                .as_millis() as usize,
            first_token_time: None,
            swapped_time: None,
            status: SequenceStatus::Waiting,
            token_ids: token_ids.clone(),
            output_ids: Vec::new(),
            block_table: Vec::new(),
            num_cached_tokens: 0,
            mamba_prefix_hash: None,
            sampling_params,
            block_size,
            last_token: *token_ids.last().unwrap_or(&0),
            pd_first_token: None,
            images,
            is_tool_call_end: false,
            hit_stop_sequence: false,
            stop_sequence: None,
        }
    }

    pub fn tokens_len(&self) -> usize {
        self.token_ids.len()
    }

    pub fn len(&self) -> usize {
        self.token_ids.len()
    }

    pub fn output_len(&self) -> usize {
        self.output_ids.len()
    }

    pub fn is_finished(&self) -> bool {
        self.status == SequenceStatus::Finished
            || self.status == SequenceStatus::Cached
            || self.status == SequenceStatus::FinishSwapped
    }

    pub fn num_blocks(&self) -> usize {
        self.len().div_ceil(self.block_size)
    }

    pub fn last_block_num_tokens(&self) -> usize {
        self.len() - (self.num_blocks() - 1) * self.block_size
    }

    pub fn num_cached_blocks(&self) -> usize {
        self.num_cached_tokens / self.block_size
    }

    pub fn append_token(&mut self, token: u32) {
        self.token_ids.push(token);
        self.output_ids.push(token);
        self.last_token = token;
    }

    pub fn block(&self, index: usize) -> Vec<u32> {
        let start = index * self.block_size;
        let end = (index + 1) * self.block_size;
        self.token_ids[start..end.min(self.token_ids.len())].to_vec()
    }

    pub fn created_time(&self) -> usize {
        self.created_time
    }

    pub fn request_arrival_time(&self) -> usize {
        self.request_arrival_time
    }

    pub fn set_request_arrival_time(&mut self, time: usize) {
        self.request_arrival_time = time;
    }

    pub fn first_token_time(&self) -> Option<usize> {
        self.first_token_time
    }

    pub fn set_first_token_time(&mut self, time: usize) {
        self.first_token_time = Some(time);
    }

    pub fn ttft(&self) -> Option<f64> {
        if let Some(first_token_time) = self.first_token_time {
            Some((first_token_time - self.request_arrival_time) as f64 / 1000.0)
        } else {
            None
        }
    }

    pub fn swapped_time(&self) -> Option<usize> {
        self.swapped_time
    }

    pub fn clear_block_table(&mut self) {
        self.block_table.clear();
    }
}
