// src/core/sequence.rs
use crate::utils::config::SamplingParams;
use crate::utils::image::ImageData;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};
#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone, Copy)]
pub enum SequenceStatus {
    Waiting,
    Running,
    Finished,
    Cached,        //Finished but resources not freed
    Swapped,       //kv cache swapped to CPU memory (may not finished)
    FinishSwapped, //Finished and kv cache swapped to CPU memory
}

impl fmt::Display for SequenceStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            SequenceStatus::Waiting => "Waiting",
            SequenceStatus::Running => "Running",
            SequenceStatus::Finished => "Finished",
            SequenceStatus::Cached => "Cached",
            SequenceStatus::Swapped => "Swapped",
            SequenceStatus::FinishSwapped => "FinishSwapped",
        };
        write!(f, "{}", s)
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Sequence {
    pub id: usize,
    pub created_time: usize,
    pub swapped_time: Option<usize>,
    pub status: SequenceStatus,
    pub token_ids: Vec<u32>,
    pub output_ids: Vec<u32>,
    pub block_table: Vec<u32>,
    pub num_cached_tokens: usize,
    pub mamba_prefix_hash: Option<u64>,
    #[serde(skip)]
    pub mamba_prefix_warmup_tokens: Option<usize>,
    pub last_token: u32,
    pub block_size: usize,
    pub sampling_params: SamplingParams,
    pub pd_first_token: Option<u32>, // the first token generated by PD server
    pub images: Option<ImageData>,   // Multimodel image data
    pub is_tool_call_end: bool,
    pub hit_stop_sequence: bool,
    pub stop_sequence: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct DecodeSequence {
    pub id: usize,
    pub last_token: u32,
    pub len: usize,
    pub last_block_tokens: usize,
    pub block_table_last: u32,
    pub block_tables: Vec<u32>,
    pub sampling_params: SamplingParams,
}

impl DecodeSequence {
    pub fn new(sequence: &Sequence) -> Self {
        let last_token = sequence.last_token;
        let len = sequence.len();
        let last_block_tokens = sequence.last_block_num_tokens();
        let block_table_last = *sequence.block_table.last().unwrap();
        DecodeSequence {
            id: sequence.id,
            last_token,
            len,
            last_block_tokens,
            block_table_last,
            block_tables: sequence.block_table.clone(),
            sampling_params: sequence.sampling_params.clone(),
        }
    }

    pub fn tokens_len(&self) -> usize {
        self.len
    }
}

pub trait ToDecodeInput {
    fn last_token(&self) -> u32;
    fn len(&self) -> usize;
    fn last_block_tokens(&self) -> usize;
    fn block_table_last(&self) -> u32;
    fn block_table(&self) -> &Vec<u32>;
    fn id(&self) -> usize;
}

impl ToDecodeInput for DecodeSequence {
    fn last_token(&self) -> u32 {
        self.last_token
    }

    fn len(&self) -> usize {
        self.len
    }

    fn last_block_tokens(&self) -> usize {
        self.last_block_tokens
    }

    fn block_table_last(&self) -> u32 {
        self.block_table_last
    }

    fn block_table(&self) -> &Vec<u32> {
        &self.block_tables
    }

    fn id(&self) -> usize {
        self.id
    }
}

impl ToDecodeInput for &Sequence {
    fn last_token(&self) -> u32 {
        self.last_token
    }

    fn len(&self) -> usize {
        self.tokens_len()
    }

    fn last_block_tokens(&self) -> usize {
        self.last_block_num_tokens()
    }

    fn block_table_last(&self) -> u32 {
        *self.block_table.last().unwrap()
    }

    fn block_table(&self) -> &Vec<u32> {
        &self.block_table
    }

    fn id(&self) -> usize {
        self.id
    }
}

impl Sequence {
    pub fn new(
        token_ids: Vec<u32>,
        block_size: usize,
        sampling_params: SamplingParams,
        images: &Option<ImageData>,
        image_idx: i32,
    ) -> Self {
        let images = if let Some(img) = &images {
            let mut img = img.clone(); // update the images
            img.image_idx = image_idx;
            Some(img)
        } else {
            None
        };
        Self {
            id: 0, // Will be set by scheduler
            created_time: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("Time went backwards")
                .as_millis() as usize,
            swapped_time: None,
            status: SequenceStatus::Waiting,
            token_ids: token_ids.clone(),
            output_ids: Vec::new(),
            block_table: Vec::new(),
            num_cached_tokens: 0,
            mamba_prefix_hash: None,
            mamba_prefix_warmup_tokens: None,
            sampling_params,
            block_size,
            last_token: *token_ids.last().unwrap_or(&0),
            pd_first_token: None,
            images,
            is_tool_call_end: false,
            hit_stop_sequence: false,
            stop_sequence: None,
        }
    }

    pub fn tokens_len(&self) -> usize {
        self.token_ids.len()
    }

    pub fn len(&self) -> usize {
        self.token_ids.len()
    }

    pub fn output_len(&self) -> usize {
        self.output_ids.len()
    }

    pub fn is_finished(&self) -> bool {
        self.status == SequenceStatus::Finished
            || self.status == SequenceStatus::Cached
            || self.status == SequenceStatus::FinishSwapped
    }

    pub fn num_blocks(&self) -> usize {
        self.len().div_ceil(self.block_size)
    }

    pub fn last_block_num_tokens(&self) -> usize {
        self.len() - (self.num_blocks() - 1) * self.block_size
    }

    pub fn num_cached_blocks(&self) -> usize {
        self.num_cached_tokens / self.block_size
    }

    pub fn prefill_chunk_tokens(&self, default_chunk_size: usize) -> usize {
        let remaining = self.len().saturating_sub(self.num_cached_tokens);
        if remaining == 0 {
            return 0;
        }
        if let Some(target_tokens) = self.active_mamba_prefix_warmup_target() {
            return (target_tokens - self.num_cached_tokens).min(default_chunk_size);
        }
        remaining.min(default_chunk_size)
    }

    pub fn active_mamba_prefix_warmup_target(&self) -> Option<usize> {
        if let Some(target_tokens) = self.mamba_prefix_warmup_tokens {
            if target_tokens > self.num_cached_tokens && target_tokens < self.len() {
                return Some(target_tokens);
            }
        }
        None
    }

    pub fn clear_mamba_prefix_warmup(&mut self) {
        self.mamba_prefix_warmup_tokens = None;
    }

    pub fn clone_for_prefill_forward(&self) -> Self {
        let mut seq = self.clone();
        if let Some(target_tokens) = self.active_mamba_prefix_warmup_target() {
            seq.token_ids.truncate(target_tokens);
            if let Some(&last_token) = seq.token_ids.last() {
                seq.last_token = last_token;
            }
        }
        seq.clear_mamba_prefix_warmup();
        seq
    }

    pub fn append_token(&mut self, token: u32) {
        self.token_ids.push(token);
        self.output_ids.push(token);
        self.last_token = token;
    }

    pub fn block(&self, index: usize) -> Vec<u32> {
        let start = index * self.block_size;
        let end = (index + 1) * self.block_size;
        self.token_ids[start..end.min(self.token_ids.len())].to_vec()
    }

    pub fn created_time(&self) -> usize {
        self.created_time
    }

    pub fn swapped_time(&self) -> Option<usize> {
        self.swapped_time
    }

    pub fn clear_block_table(&mut self) {
        self.block_table.clear();
    }
}

#[cfg(test)]
mod tests {
    use super::Sequence;
    use crate::utils::config::SamplingParams;

    fn test_sequence(len: usize) -> Sequence {
        Sequence::new(
            (0..len as u32).collect(),
            64,
            SamplingParams::default(),
            &None,
            -1,
        )
    }

    #[test]
    fn prefill_chunk_tokens_uses_mamba_warmup_boundary() {
        let mut seq = test_sequence(20_000);
        seq.num_cached_tokens = 0;
        seq.mamba_prefix_warmup_tokens = Some(5_824);

        assert_eq!(seq.prefill_chunk_tokens(8_192), 5_824);

        seq.num_cached_tokens = 5_824;
        assert_eq!(seq.prefill_chunk_tokens(8_192), 8_192);
    }

    #[test]
    fn prefill_chunk_tokens_tracks_multi_chunk_mamba_warmup_boundary() {
        let mut seq = test_sequence(50_000);
        seq.mamba_prefix_warmup_tokens = Some(20_000);

        assert_eq!(seq.prefill_chunk_tokens(8_192), 8_192);

        seq.num_cached_tokens = 8_192;
        assert_eq!(seq.prefill_chunk_tokens(8_192), 8_192);

        seq.num_cached_tokens = 16_384;
        assert_eq!(seq.prefill_chunk_tokens(8_192), 3_616);

        seq.num_cached_tokens = 20_000;
        assert_eq!(seq.prefill_chunk_tokens(8_192), 8_192);
    }

    #[test]
    fn prefill_chunk_tokens_ignores_invalid_mamba_warmup_boundary() {
        let mut seq = test_sequence(10_000);
        seq.num_cached_tokens = 4_096;
        seq.mamba_prefix_warmup_tokens = Some(4_096);

        assert_eq!(seq.prefill_chunk_tokens(8_192), 5_904);

        seq.mamba_prefix_warmup_tokens = Some(12_000);
        assert_eq!(seq.prefill_chunk_tokens(8_192), 5_904);
    }

    #[test]
    fn clone_for_prefill_forward_truncates_to_mamba_warmup_boundary() {
        let mut seq = test_sequence(10_000);
        seq.num_cached_tokens = 0;
        seq.mamba_prefix_warmup_tokens = Some(5_824);

        let forward = seq.clone_for_prefill_forward();

        assert_eq!(forward.len(), 5_824);
        assert_eq!(forward.last_token, 5_823);
        assert_eq!(forward.prefill_chunk_tokens(8_192), 5_824);
        assert_eq!(seq.len(), 10_000);
    }

    #[test]
    fn clone_for_prefill_forward_ignores_warmup_after_cached_prefix() {
        let mut seq = test_sequence(10_000);
        seq.num_cached_tokens = 8_192;
        seq.mamba_prefix_warmup_tokens = Some(8_320);

        let forward = seq.clone_for_prefill_forward();

        assert_eq!(seq.prefill_chunk_tokens(8_192), 128);
        assert_eq!(forward.len(), 8_320);
        assert_eq!(forward.prefill_chunk_tokens(8_192), 128);
    }

    #[test]
    fn clone_for_prefill_forward_truncates_multi_chunk_warmup_after_cached_prefix() {
        let mut seq = test_sequence(50_000);
        seq.num_cached_tokens = 8_192;
        seq.mamba_prefix_warmup_tokens = Some(20_000);

        let forward = seq.clone_for_prefill_forward();

        assert_eq!(forward.len(), 20_000);
        assert_eq!(forward.last_token, 19_999);
        assert_eq!(forward.prefill_chunk_tokens(8_192), 8_192);
    }

    #[test]
    fn mamba_warmup_boundary_is_not_serialized() {
        let mut seq = test_sequence(10_000);
        seq.mamba_prefix_warmup_tokens = Some(5_824);

        let encoded = bincode::serialize(&seq).unwrap();
        let decoded: Sequence = bincode::deserialize(&encoded).unwrap();

        assert_eq!(decoded.len(), seq.len());
        assert_eq!(decoded.mamba_prefix_warmup_tokens, None);
    }
}
